lastupdatecheck: 0
recentrepos:
- /Users/tentzp/Code/ali/it-xiaoge-desktop
- /Users/tentzp/Code/tools/workstation-bootstrap
startuppopupversion: 0
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
